In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
# Creat a model class tha inherits nn.module :
class Model(nn.Module):
  # input layer (4 feature of flower)-->
  # Hidden layer (number of neurons)-->
  # Hidden layer 2(number of neurons)-->
  # output layer(3 classes of iris flower).
  def __init__(self,inp_features = 4, h1 = 8, h2 = 9, out_features = 3):
    super().__init__()   # instantiate our nn.module

    # in line below fc1 is fully connection between neurons :

    # in the lines below the data moving first form input features to hidden line one
    self.fc1 = nn.Linear(inp_features, h1)

    #  in the line below the data is moving form hidden line 1 to hidden line 2:
    self.fc2 = nn.Linear(h1, h2)

    #  in the line below the data is moving form hidden line to out put:
    self.out = nn.Linear(h2, out_features)

    # now we need function that moving everything forward so :
    def forward(self, x):
      x = F.relu(self.fc1(x))
      x = F.relu(self.fc1(x))
      x = F.relu(self.out(x))
      return x


In [ ]:
# here before we turn the function on we need to create mannual_seed:
torch.manual_seed(41)
model = Model()

In [ ]:
# now wr going to import matplotlib because we are going ti make a little chart later on it the end:
import matplotlib

In [ ]:
import torch

print("PyTorch version:", torch.__version__)


PyTorch version: 2.2.1+cu121


In [ ]:
tensor1 = torch.tensor([1, 2, 3, 4, 5])

In [ ]:
scalar = torch.tensor(7)

In [ ]:
scalar

tensor(7)

# **INTRODUCTON TO TENSOR:**

In [ ]:
scalar = torch.tensor(7)

In [ ]:
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
vector = torch.tensor([1, 2, 3])

In [ ]:
vector.ndim

1

# **Initializing and basic operations**

In [ ]:
import numpy as np
torch1 = torch.tensor([[1., -1.], [1., -1.]])
torch1.ndim

2

In [ ]:
torch2 = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
torch2.ndim


2

# **tensor of specific data type**

In [ ]:
torch3 = torch.zeros([2, 4,3], dtype=torch.int32)    # (column, rows, dimension)
print(torch3)
torch3.ndim

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=torch.int32)


3

In [ ]:
torch4 = torch.ones([3, 4, 3], dtype=torch.float64)
print(torch4)
torch4.ndim
torch4.dtype

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]], dtype=torch.float64)


torch.float64

In [ ]:
import torch

# Generate a tensor of random numbers with a specific shape
random_tensor = torch.randn(2,3,3)

# Print the random tensor
print("Random Tensor:")
print(random_tensor)


Random Tensor:
tensor([[[-2.7412, -1.1016, -0.7810],
         [-1.1971, -2.3150, -1.1734],
         [ 1.1527, -0.2896,  0.9425]],

        [[-0.8061,  0.4900, -1.2069],
         [ 0.0617, -0.1109, -0.7134],
         [ 0.4185,  0.7577,  0.9829]]])


In [ ]:
import torch

# Generate a tensor of random integers with a specific shape
random_tensor = torch.randint(low=0, high=100, size=(1,))  # Generates a 3x3 tensor of random integers between 0 and 100

# Print the random tensor
print("Random Tensor:")
print(random_tensor)


Random Tensor:
tensor([20])


# **Lucky Number Game! with random number**

In [ ]:
import torch

def generate_random_number():
    return torch.randint(low=1, high=10, size=(1,)).item()

def play_game():
    attempts = 0
    max_attempts = 5
    random_number = generate_random_number()

    while True:
        user_input = input("Enter your lucky number (between 1 and 10): ")

        # Check if user input is a valid integer
        try:
            user_guess = int(user_input)
        except ValueError:
            print("Please enter a valid integer.")
            continue

        attempts += 1

        # Check if user's guess matches the random number
        if user_guess == random_number:
            print("Congratulations! Your lucky number matches the random number:", random_number)
            break
        else:
            difference = abs(user_guess - random_number)
            print(f"Sorry, try again. You are {difference} numbers away from the random number.")

        # If the user exceeds the maximum attempts, generate a new random number
        if attempts >= max_attempts:
            random_number = generate_random_number()
            attempts = 0
            print("New random number generated. Try again!")

if __name__ == "__main__":
    print("Welcome to the Lucky Number Game!")
    print("You have 5 attempts to guess the lucky number.")
    play_game()


Welcome to the Lucky Number Game!
You have 5 attempts to guess the lucky number.
Enter your lucky number (between 1 and 10): 6
Sorry, try again. You are 1 numbers away from the random number.
Enter your lucky number (between 1 and 10): 5
Congratulations! Your lucky number matches the random number: 5


# image size with random

In [ ]:
import torch
import random
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor,random_image_size_tensor.shape, random_image_size_tensor.ndim


(tensor([[[0.4514, 0.8786, 0.2152],
          [0.2135, 0.5005, 0.3748],
          [0.0591, 0.9862, 0.0089],
          ...,
          [0.3068, 0.3345, 0.0920],
          [0.7135, 0.0399, 0.2473],
          [0.2517, 0.2399, 0.4335]],
 
         [[0.6665, 0.4833, 0.0018],
          [0.8023, 0.9286, 0.6778],
          [0.6418, 0.8708, 0.3403],
          ...,
          [0.0601, 0.1003, 0.8187],
          [0.8929, 0.1135, 0.2328],
          [0.6211, 0.4498, 0.9561]],
 
         [[0.3639, 0.3070, 0.0122],
          [0.4496, 0.6539, 0.9578],
          [0.0993, 0.2848, 0.3014],
          ...,
          [0.3418, 0.4471, 0.4243],
          [0.5551, 0.6007, 0.3293],
          [0.7352, 0.0550, 0.6412]],
 
         ...,
 
         [[0.9329, 0.4338, 0.4317],
          [0.8223, 0.6056, 0.1623],
          [0.3452, 0.5361, 0.6289],
          ...,
          [0.3418, 0.1827, 0.2855],
          [0.1457, 0.4114, 0.0366],
          [0.0158, 0.4863, 0.6731]],
 
         [[0.1003, 0.9758, 0.2055],
          [0

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, #ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),)

In [ ]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=11, step=3)
zero_to_ten

<ipython-input-27-d9fa3db1730a>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 3, 6, 9])

In [ ]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.ones_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([1, 1, 1, 1])

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.5084, 0.8689, 0.8870, 0.0088],
        [0.9337, 0.8602, 0.1685, 0.6135],
        [0.9793, 0.1122, 0.7116, 0.9409]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# **Basic operations**

In [ ]:
# Create a tensor of values and add a number to it
import torch
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [ ]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

# **Element-wise multiplication**

In [ ]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)         #(1*1, 2*2, 3*3)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
import torch
tensor = torch.tensor([[1, 4, 9]])
tensor.shape

torch.Size([1, 3])

# **matrix multiplication**

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor.matmul(tensor)                    #(1*1 +2*2  +3*3)

tensor(14)

In [ ]:
import torch
zero =  torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
import torch
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],dtype = torch.float32)
print(float_32_tensor, float_32_tensor.dtype)

tensor([3., 6., 9.]) torch.float32


# **Most common Error in deep learning**

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
tensor_B = torch.tensor([[2, 3],
                         [3, 4],
                         [4, 2]], dtype = torch.float32)

# Error due to inner dimension

In [ ]:
torch.mm(tensor_A, tensor_B)   # it will gives an error:

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
S

# **Solution for the error:**
## is to take transpose of one matrics to convert column into rows and vise versa

In [ ]:
print(tensor_A)
print(tensor_B.T)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[2., 3., 4.],
        [3., 4., 2.]])


In [ ]:
#torch.mm as a structure for the matmul:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 8., 11.,  8.],
        [18., 25., 20.],
        [28., 39., 32.]])

# **tensor with matmul and with loop:**

In [ ]:
import torch
# import time
%time
tensor = torch.tensor([1, 2, 3])
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)


CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.15 µs
tensor(14)


In [ ]:
%time
torch.matmul(tensor, tensor)
# print(tensor)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.48 µs


tensor(14)

# Finding the Min, Max, Mean, sum etc (aggregation).

In [ ]:
# ist we will create tensor:
import torch
X = torch.arange(0, 100, 10)
print(X)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


# performing operation on above tensor

In [ ]:
print(f"Minimum of above tensor: {X.min()}")
print(f"Maximum of above tensor: {X.max()}")
print(f"Mean of above tensor: {X.type(torch.float16).mean()}")
print(f"Sum of above tensor: {X.sum()}")
print(f"Mean of above tensor: {X.type(torch.float32).mean()}")
print(f"Mean of above tensor: {X.type(torch.float64).mean()}")


Minimum of above tensor: 0
Maximum of above tensor: 90
Mean of above tensor: 45.0
Sum of above tensor: 450
Mean of above tensor: 45.0
Mean of above tensor: 45.0


In [ ]:
Z = torch.arange(100, 200, 15)
print(Z)

tensor([100, 115, 130, 145, 160, 175, 190])


In [ ]:
# Positional maximum and minimum of tensor:
print(f'Maximum of tensor_Z is : {Z.max(), Z.argmax()}')
print(f'Minimum of tensor_Z is : {Z.min(), Z.argmin()}')
print(f'Mean of tensor_Z is : {Z.type(torch.float16).mean()}')
print(f'Sum of tensor_Z is : {Z.sum()}')

Maximum of tensor_Z is : (tensor(190), tensor(6))
Minimum of tensor_Z is : (tensor(100), tensor(0))
Mean of tensor_Z is : 145.0
Sum of tensor_Z is : 1015


# must look after the common issue of datatype
#### the tensor should be in same dtype to be used for any kind of operation in future other wise you will face error so must keep the datatype of your tensor same before using for any kind of operation by defult dtype of any tensor is float32 lets create and check for the datatype

In [ ]:
x =  torch.arange(10., 100., 10.)
print(x.dtype, x)

torch.float32 tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])


In [ ]:
# as we see by defulat the datatype was float32 now we will create the same tensor but will set the datatype
x_float16 = x.type(torch.float16)
print(x_float16)

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)


# Creation of random tensor:
### for the creation of random tensor we will use torch.rand() and will pass a size as a perameter:
### the flexibilty of torch.rand() is that we can adjust the size to be what ever we want


In [ ]:
# lets create a random tesnor of any size you want
import torch
random_tensor = torch.rand(2, 3)
print(random_tensor, random_tensor.dtype)

tensor([[0.4914, 0.1562, 0.3248],
        [0.4576, 0.4660, 0.3196]]) torch.float32



# Creating a range and tensors like

In [ ]:
# we will use torch.arange, torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # this may retun an error in future

# create a range of value 0 to 10
zero_to_ten = torch.arange(start = 0, end = 10, step = 1)
print(zero_to_ten)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


<ipython-input-3-0526ccf8d59a>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # this may retun an error in future


## some time we want one tensor of certain type with same shape as another tensor.
### For example, a tensor of all zeros with same shape as a previous tensor.
### To do so you can use--->... **torch.zeros_like(input)** or **torch.ones_like (input)** respectively

In [ ]:
# now we will create a tensor of zeros similar to another tensor:
ten_zeros = torch.zeros_like(input = zero_to_ten, dtype = torch.float32)
print(ten_zeros, ten_zeros.dtype)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) torch.float32


In [ ]:
# in this section now we will create the tensor of ones similar to another tensor:
ten_ones = torch.ones_like(input = zero_to_ten, dtype =  torch.int32)
print(ten_ones)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.int32)


# dtype
## There are many different tensor dtattypes avalibale in pytorc. Some are specific for CPU and some are specific for GPU.

In [ ]:
# now lets see how to create some tensor with specific data type . We can do so using te dtype parameter.
# default dtype for tensor is float32:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)
print(float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device)

torch.Size([3]) torch.float32 cpu


# 3 most common issues:
## tensor.shape
## tensor.dtype
## tensor.device issue


In [ ]:
# for now lets create a tensor with dtype = torch.float16:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16)
print(float_16_tensor)

tensor([3., 6., 9.], dtype=torch.float16)


# **Getting information from tensors:**
### we've seen these before but three of the most common attributes you'll want to find out about tensor are:
## **shape**:
### what shape is the tensor?(some operation require specific shape rules)
## **dtype**:
### what datatype are the elements within the tensor stored in ?
## **device**:
### what device is the tensor stored on?(usually GPU OR CPU)

In [ ]:
# Lets create tensor with some number you want:
some_tensor = torch.rand(3, 4)
# Find out details about it:
print(some_tensor)
print(f"The shape of tensor is: {some_tensor.shape}")
print(f"The dtype of tensor is: {some_tensor.dtype}")
print(f"The device of tensor stored on: {some_tensor.device}")

tensor([[0.6179, 0.1652, 0.7747, 0.5404],
        [0.4326, 0.5829, 0.4941, 0.8683],
        [0.7662, 0.3327, 0.9478, 0.3886]])
The shape of tensor is: torch.Size([3, 4])
The dtype of tensor is: torch.float32
The device of tensor stored on: cpu


# Reshaping, stacking, squeezing and unsqueezing
## Durnig the training many time we will want to reshape or change the dimensions of our tensor without actually changing the values inside them

In [ ]:
# lets create tensor:
import torch
S = torch.arange(1., 9.)
print(S, S.shape, S.dtype)

tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8]) torch.float32


# **Reshaping**
## now we will add extra dimension to the above tensor with the following code:
**torch.reshape()**

In [ ]:
# let start with reshape to add an extra dimension:
# The important thik to be in mind about reshape is that the dimensions should be compatible to the original dimension:

S_reshaped = S.reshape(1, 8)    # (rows, column)    # if the perameter given to the reshape() method are less or greater then the actuall tensor it will cause error
# S_error = S.reshape(3,2)       # shape '[3, 2]' is invalid for input of size 8
print(S_reshaped)

tensor([[ 1.,  2.,  3.,  4., 55.,  6.,  7.,  8.]])


# **view**
## return a view of an input tensor of certain shape but keep the same memory as the original tensor

In [ ]:
# lets try to change the view:
V = S.view(1,8)
print(V,  V.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]) torch.Size([1, 8])


# **Change in view:**
## Changing V changes S (Because a view of a tensor share the same memory as the original input)

In [ ]:
# lets try a change in view:
V[:, 4] = 55     # this will change the element of both view and original because view effect the original one :

print(V , S)

tensor([[ 1.,  2.,  3.,  4., 55.,  6.,  7.,  8.]]) tensor([ 1.,  2.,  3.,  4., 55.,  6.,  7.,  8.])


# **Stacking :**
## combine multipe tensors on top os each other (vstack) or side by side (hstack) along a new dimension

In [ ]:
# lets try stacking where we will stack tensor on the top of each other
S_stacked = torch.stack([S,S,S,S], dim = 0)  # we can also chane the dimension to 1:
print(S_stacked, S_stacked.dtype, S_stacked.shape)

tensor([[ 1.,  2.,  3.,  4., 55.,  6.,  7.,  8.],
        [ 1.,  2.,  3.,  4., 55.,  6.,  7.,  8.],
        [ 1.,  2.,  3.,  4., 55.,  6.,  7.,  8.],
        [ 1.,  2.,  3.,  4., 55.,  6.,  7.,  8.]]) torch.float32 torch.Size([4, 8])


# **Squeeze:**
## remove all "1" dimensions from a tensor

In [ ]:
print(f"previous tesnor:{S_reshaped}")
print(f"previous tesnor:{S_reshaped.shape}")

#Using squeeze to remove all the extra dimensions form the tensor:
S_squeezed =  S_reshaped.squeeze()
print(f"\nNew Tensor: {S_squeezed}")
print(f"\nNew shape : {S_squeezed.shape}")

# notice the change in the previouse tensor and new tensor dimensions you will find the difference :

previous tesnor:tensor([[ 1.,  2.,  3.,  4., 55.,  6.,  7.,  8.]])
previous tesnor:torch.Size([1, 8])

New Tensor: tensor([ 1.,  2.,  3.,  4., 55.,  6.,  7.,  8.])

New shape : torch.Size([8])


# **unsqueeze:**
## add a "1" dimension to a target tensor

In [ ]:
# torch.unsqueeze add a single dimension to a target tensor at a specific dimension:
print(f"previous target:{S_squeezed}")
print(f"previous tesnor:{S_squeezed.shape}")

#Using unsqueeze to add one single dimensions to a target tensor:
S_unsqueezed =  S_squeezed.unsqueeze(dim = 1)
print(f"\nNew Tensor: {S_unsqueezed}")
print(f"\nNew shape : {S_unsqueezed.shape}")

# notice the change in the previouse tensor and new tensor dimensions you will find the difference :

previous target:tensor([ 1.,  2.,  3.,  4., 55.,  6.,  7.,  8.])
previous tesnor:torch.Size([8])

New Tensor: tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [55.],
        [ 6.],
        [ 7.],
        [ 8.]])

New shape : torch.Size([8, 1])


# **Permute:**
## return a view of the input with dimension permuted(swapped) in a certain way:

In [ ]:
# torch.permute : rearrange the dimension of a taret tensor in a specified order:
S_original = torch.rand(size = (224, 224, 3))      #(height, width, color_cannels)

# permute the original tensor to rearrange the axis or dimensions or order
S_permuted = S_original.permute(2, 0, 1)   # shifts axis 0-> 1, 1-> 2, 2-> 0
print(f"previous shape : {S_original.shape}")
print(f"new shape : {S_permuted.shape}")


previous shape : torch.Size([224, 224, 3])
new shape : torch.Size([3, 224, 224])


# **Indexing**(selecting data form tesnors)
sometime we will want to select specific data from tesnor(for example, only first column or secend row)


In [ ]:
# lets create a tensor
import torch
tensor_1 = torch.arange(1, 10).reshape(1, 3, 3)
print(tensor_1, tensor_1.shape, tensor_1.ndim)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3]) 3


In [ ]:
tensor_1[:, 1:, :]

tensor([[[4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# lets try to get all value of the 0th index of 1st dimension
tensor_1[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# to get all values of 0th and 1st dimension but only index of 1 and 2nd dimension
tensor_1[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
tensor_1[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
tensor_1[:, 0, :]

tensor([[1, 2, 3]])

# **PyTorch tensors & NumPy**
numpy is popular pyhton numerical computing library, pytorch has functionality to interact with it nicely.
The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

**torch.from_numpy(ndarray)** - NumPy array -> PyTorch tensor.
**torch.Tensor.numpy()** - PyTorch tensor -> NumPy array.

In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
"""
Note: By default, NumPy arrays are created with the datatype float64
and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).
However, many PyTorch calculations default to using float32.
So if you want to convert your NumPy array (float64) ->
PyTorch tensor (float64) -> PyTorch tensor (float32),
you can use tensor = torch.from_numpy(array).type(torch.float32).
"""
tensor_float32 = torch.from_numpy(array).type(torch.float32)


array, tensor, tensor_float32, tensor_float32.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [ ]:
# change the array, keep the tensor
array = array + 1
print(array, tensor)

[2. 3. 4. 5. 6. 7. 8.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


# **PyTorch tensor to NumPy array**
you can call **tensor.numpy()**.

In [ ]:
# lets try to convert the tensor to numpy:
tensor = torch.ones(7)       # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy()
print(tensor, numpy_tensor, numpy_tensor.dtype)
type(numpy_tensor)

tensor([1., 1., 1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1. 1. 1.] float32


numpy.ndarray

In [ ]:
# if you change the original tensor, the new numpy_tensor stays the same.
tensor = tensor + 1
print(tensor, numpy_tensor)

tensor([2., 2., 2., 2., 2., 2., 2.]) [1. 1. 1. 1. 1. 1. 1.]


# **Reproducibility** (trying to take the random out of random)
As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

In [ ]:
# The followig code will create two tensor of each different number of both tensors:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B
# the output of this code will be false for every element of both tensors:


Tensor A:
tensor([[0.6937, 0.4867, 0.9161, 0.6645],
        [0.9379, 0.3326, 0.7756, 0.0311],
        [0.7886, 0.0667, 0.1767, 0.0215]])

Tensor B:
tensor([[0.0522, 0.9167, 0.3835, 0.7838],
        [0.5523, 0.5452, 0.0732, 0.1931],
        [0.9717, 0.7818, 0.6802, 0.0374]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

# **tensor with same random numbers**
if you wanted to created two random tensors with the same values.
As in, the tensors would still contain random values but they would be of the same flavour.

That's where torch.manual_seed(seed) comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.

Let's try it out by creating some more flavoured random tensors.

# **RANDOM_SEED**
The seed is used to initialize the pseudorandom number generator in Python. The random module uses the seed value as a base to generate a random number. if seed value is not present it takes system current time. if you provide same seed value before generating random data it will produce the same data.

In [ ]:
import torch
import random

# Set the random seed
RANDOM_SEED=44                    # try changing the value "43" to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

# look for the output:
print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D
# this wil output true for each element of both the tensors:

Tensor C:
tensor([[0.7196, 0.7307, 0.8278, 0.1343],
        [0.6280, 0.7297, 0.2882, 0.2112],
        [0.9836, 0.8722, 0.9650, 0.7837]])

Tensor D:
tensor([[0.7196, 0.7307, 0.8278, 0.1343],
        [0.6280, 0.7297, 0.2882, 0.2112],
        [0.9836, 0.8722, 0.9650, 0.7837]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])